johnvardanyan/CtrlAltDelete

- frontend/src/css/Navbar.css
- frontend/src/css/TaskForm.css
- frontend/src/pages/Overview.js
- frontend/src/pages/TaskForm.js
Finalized the Create Task page. Added fields for task title, due date, priority, assigned employee, and description. Add employee and remove employee buttons are functional. Made css design match the mockup.
Made slight changes to other files to fix errors / change inconsistencies in color.
> JIRA/NM-89, JIRA/NM-90, JIRA/NM-91, JIRA/NM-92, JIRA/NM-94, JIRA/NM-125

- frontend/src/pages/History.js
Added filter by date and reset filter options
> NM - 103, 105

- frontend/src/App.js
- frontend/src/context/TasksContext.js
- frontend/src/pages/EditHistory.js
- frontend/src/pages/Overview.js
Created editHistory page and edit task functionality
> JIRA/NM - 111, 112, 113, 114

- frontend/src/css/Overview.css
- frontend/src/pages/Overview.js
Moved all CSS into one Overview container, Changed variable names to portray actual, Fixed task boy layout.
> NM-148, 149, 152

- frontend/src/css/Overview.css
- frontend/src/pages/Overview.js
NM 171 - Fixed the status of 'priority shown' on the overview page and aligned the filter section of the overview page with that of the history page. 
NM 173 – Worked on the  “Mark Complete” Button
> JIRA  NM-171&173

- frontend/src/css/Overview.css
- frontend/src/pages/Overview.js
Fix functionality of filters & fixed CSS to match home page
> NM-177 & Nm-178

- backend/controllers/userController.js
- backend/models/userModel.js
- backend/models/verificationToken.js
- backend/package-lock.json
- backend/package.json
- backend/routes/user.js
- backend/utils/mail.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/hooks/useAuthContext.js
- frontend/src/hooks/useLogin.js
- frontend/src/hooks/useVerify.js
- frontend/src/pages/EditHistory.js
- frontend/src/pages/Profile.js
- frontend/src/pages/Signup.js
- frontend/src/pages/Verification.js
- package-lock.json
- package.json
Backend: Created User DB for users & verification Token DB for user email verification OTP and Email OTP verification functionality that verifies users.
Frontend: Added verification OTP page after clicking signup which allows users to input OTP received in email.
> JIRA/NM - 181,183,202,203,205,

- backend/models/taskModel.js
- frontend/src/pages/History.js
- frontend/src/pages/Home.js
- frontend/src/pages/Overview.js
Task 106 involved adjusting the filters in the homepage and overview so that when a task is marked complete in the overview, it disappears from the the overview and home page and only shows up in the history page marked as "complete" in the top right corner of the tasks. (note: you have to refresh the page or switch to another page for this effect to take place)
Task 210 involved just adjusting the filters in the home and overview page to ignore deleted tasks, and for the history page to show deleted tasks. For now, the only way to test this is to set the default deleted status of the schema task to true and create a task. This deleted tasks should then only show up in the history page and no where else.
The taskModel.js edit was just a small edit to remove unnecessary code.
> NM-106,210

- frontend/src/App.js
- frontend/src/css/Bottombar.css
- frontend/src/css/Calendar.css
- frontend/src/css/Navbar.css
- frontend/src/index.css
- frontend/src/pages/Calendar.js
1. The calendar now shows past due tasks.
2. Side container added next to the calendar for displaying info.
3. Clicking a task on the calendar shows its info in the new side container (pop-up).
4. Styling done.
> Jeremy's commits

- backend/controllers/taskController.js
- backend/controllers/userController.js
- backend/middleware/requireAuth.js
- backend/models/taskModel.js
- backend/models/userModel.js
- backend/routes/user.js
- backend/server.js
- frontend/src/components/TaskDetails.js
- frontend/src/pages/TaskForm.js
> JIRA/NM -142-143 Complete

- backend/models/userModel.js
- frontend/src/components/TaskDetails.js
- frontend/src/css/TaskDetails.css
- frontend/src/pages/Calendar.js
- package.json
NM - 192: Changed the password error message from 'Password not strong enough' to a more descriptive message for when users sign up.
NM - 211: Created clickable tasks on the Calendar page and matched the color of the task boxes to the main calendar page color.
> JIRA/NM 192 & 211

- frontend/src/components/TaskDetails.js
- frontend/src/css/Calendar.css
- frontend/src/css/TaskDetails.css
> TaskDetail quickfix

- frontend/src/css/Login.css
- frontend/src/pages/Login.js
> JIRA/NM -182

- frontend/src/pages/Calendar.js
Revert the styling of the task info on the calendar page back to JIRA/NM-233.
>  Revert calendar page styling  

- backend/controllers/taskController.js
- frontend/src/css/TaskDetails.css
- frontend/src/pages/EditHistory.js
quick fix to edit history and assign employees as well as text color.
> quickfix & css

- backend/controllers/userController.js
- backend/models/userModel.js
- backend/routes/user.js
- backend/utils/mail.js
- frontend/src/App.js
- frontend/src/css/Login.css
- frontend/src/css/ResetPassword.css
- frontend/src/hooks/useForgotPassword.js
- frontend/src/hooks/useSendOTP.js
- frontend/src/hooks/useUpdatePassword.js
- frontend/src/pages/ForgotPassword.js
- frontend/src/pages/Login.js
- frontend/src/pages/Profile.js
- frontend/src/pages/ResetPassword.js
Added password reset functionality, OTP verification through email, forgot & reset password pages, bug fixes, & more.
> JIRA/NM - #184, 218, 219, 220

- backend/controllers/userController.js
- backend/middleware/user.js
- backend/models/resetToken.js
- backend/routes/user.js
- backend/utils/helper.js
- backend/utils/mail.js
- frontend/src/App.js
- frontend/src/pages/ForgotPassword.js
- frontend/src/pages/ResetPassword.js
When clicking "Forgot Password", you are able to put in your email which will send a link to your email in order to set up a new password.
> JIRA/NM - 237

- frontend/src/pages/ResetPassword.js
- package.json
If user puts in old password when trying to reset password, output the error: "Password must be different"
Updated script to install cors library
> Updated Script and Error message

- backend/controllers/userController.js
- backend/models/userModel.js
- backend/routes/user.js
Added backend code + routing to be able to delete users from DB. Additionally, added another role called 'Owner' which is automatically set to the OWNER_EMAIL that is in the environment variable.
> JIRA/NM - 190 and user roles update

- backend/models/taskModel.js
- frontend/src/css/Overview.css
- frontend/src/pages/Overview.js
Fixed the issue with message "Task was changed by.." not staying in "Edit History" box. Displayed task lifecycle of when it was created and if it was edited. Changed the CSS of the "Assigned Employee(s)", "Task Description", and "Edit History"
> NM-223,243,245

- backend/controllers/taskController.js
- backend/controllers/userController.js
- frontend/src/css/Calendar.css
- frontend/src/css/Home.css
- frontend/src/css/Overview.css
- frontend/src/css/Verification.css
- frontend/src/hooks/useVerify.js
- frontend/src/index.css
- frontend/src/pages/Calendar.js
- frontend/src/pages/EditHistory.js
- frontend/src/pages/History.js
- frontend/src/pages/Home.js
- frontend/src/pages/Overview.js
- frontend/src/pages/TaskForm.js
- frontend/src/pages/Verification.js
- package-lock.json
- package.json
NM 242- Fixed the submit button on the calendar page. Also, reworked the UI to ensure overflowing components stay inside their respective containers and fixed the functionality of the entire 'Task Information' box.
NM 214 - Fixed Time Zone issue to match across the board, and now everything is set to Pacific Time. Whole project is now synced with Pacific Time.
NM 225 - Created a graphic component to display success/error messages from the backend OTP verification.
After you pull my code, please make sure to run 'npm install' and 'npm install moment-timezone' for dependencies and then 'npm start'
> NM - #242,#214#225

- frontend/src/App.js
- frontend/src/components/Navbar.js
- frontend/src/css/ForgotPassword.css
- frontend/src/css/Navbar.css
- frontend/src/css/Profile.css
- frontend/src/css/ResetPassword.css
- frontend/src/css/Users.css
- frontend/src/pages/ForgotPassword.js
- frontend/src/pages/ResetPassword.js
- frontend/src/pages/Users.js
Added a new "Users" page where every user in the database is listed with their full name and email. Css is complete and polished for this page.
Deleted the Login/Signup buttons from the Navbar, and added the route to "Users" under the Menu drop down.
Added the css for ForgotPassword and ResetPassword pages, along with css for the actual reset password function on the Profile page. All css is consistent and neat.
> JIRA/NM - 235, 236, 239, 249, 250

- backend/controllers/userController.js
- backend/models/userModel.js
- backend/routes/user.js
- backend/server.js
- frontend/src/App.js
- frontend/src/components/Navbar.js
- frontend/src/css/Users.css
- frontend/src/pages/History.js
- frontend/src/pages/Users.js
- Added environment Variable: DOMAIN_NAME
- Added functionality of deleting users
- Added functionality of assign admin
- Added functionality of removing admin
- Only owner and admin can see "Users" page
- Owner is the only role that is not displayed in User's page
- Added notification of functionalities above
- Added CSS design: Up, Down (admin, remove admin), crown for roles (color for admin or employee)
- Added role next to name in Navbar
> JIRA/NM - 251-253, 280,281,293-295

- backend/controllers/taskController.js
- frontend/src/css/TaskForm.css
- frontend/src/hooks/useCustomFetch.js
- frontend/src/index.css
- frontend/src/pages/EditHistory.js
- frontend/src/pages/TaskForm.js
Created more descriptive error messages when creating/editing tasks with required fields. 
Created notifications when a task is successfully created/edited. 
Removed "autofill" feature on Create Task page
Fixed issue where employee list disappears after a task is created. 
Fixed priority and employee fields not correctly displaying when editing a task. 
Added date-time format to Edit Task page for consistency with Create Task page.
> NM/JIRA - NM - 254, 256, 284, 285, 291

- backend/controllers/userController.js
- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/PasswordStrengthBox.js
- frontend/src/css/Overview.css
- frontend/src/css/Verification.css
- frontend/src/hooks/useUpdatePassword.js
- frontend/src/pages/Overview.js
- frontend/src/pages/Profile.js
- frontend/src/pages/Signup.js
- frontend/src/pages/Users.js
- package-lock.json
- package.json
NM 264 - Designed a password requirement description box for the 'Change Password' and 'Sign Up' options to be used when a user changes their password or signs up as a new employee.
NM 265 - Implemented a notification if a user enters their current password incorrectly to change their password. Also, implemented the Email OTP success/fail indication design for the change password option. Now users can see all these options under the change password option.
NM 266 - Checked to ensure that all the incorrect credentials pop-ups and verified pop-ups are correctly positioned on each page. Also, moved the verification message to the same bar of admin details in the users' page under the admin login when the user clicks the up arrow to switch between 'Admin' and 'Employee' roles.
NM 275 - …
> NM - #264, 265, 266, 275

- frontend/src/components/Navbar.js
Removes (employee) from showing in the top right. Only admins and owners will show.
> Quick visual update

- frontend/src/css/Overview.css
- frontend/src/pages/Overview.js
270 - Ensure all tasks are visible while user scrolls, footer does not cut off tasks
296- Moved task boxes off the left-hand side, easier to read
297- Removed email from "Assigned Employee" task box in Overview
> NM-278, 296, 297

- backend/utils/mail.js
- frontend/src/css/Login.css
- frontend/src/css/Signup.css
- frontend/src/css/Users.css
- frontend/src/pages/Login.js
- frontend/src/pages/Signup.js
- frontend/src/pages/Users.js
- frontend/src/pages/Verification.js
CSS changes to several pages, and added filters to Users page.
> JIRA/NM - 206, 263, 268, 270, 271, 272, 273

- backend/controllers/userController.js
- backend/routes/user.js
- frontend/src/pages/ForgotPassword.js
- frontend/src/pages/Home.js
NM 305- Fixed the issue with the 'Forgot Password' link so that now users can request a password reset link as many times as they need, instead of it being sent only once.
NM 306 - Worked on the functionality of the 'Forgot Password' button, so now users can reset their password properly.
> NM - #305, #306 

- frontend/src/css/Profile.css
- frontend/src/css/TaskForm.css
- frontend/src/pages/Calendar.js
- frontend/src/pages/Profile.js
Fixed some bugs and updated CSS on final remaining pages.
> JIRA/NM - 304, 316, 317

- README.md
- package-lock.json
> John's commits
